# Generated by Django 5.2.8 on 2025-12-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('file', models.FileField(upload_to='menus/', verbose_name='PDF файл')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
            ],
            options={
                'verbose_name': 'Файл меню',
                'verbose_name_plural': 'Файлы меню',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
