# Generated by Django 5.2.9 on 2025-12-06 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(verbose_name='Номер страницы')),
                ('image', models.ImageField(upload_to='menus/pages/', verbose_name='PNG-страница')),
                ('menu_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='menus.menufile', verbose_name='Меню (PDF)')),
            ],
            options={
                'verbose_name': 'Страница меню',
                'verbose_name_plural': 'Страницы меню',
                'ordering': ['menu_file', 'page_number'],
                'unique_together': {('menu_file', 'page_number')},
            },
        ),
    ]
