# Generated by Django 5.2.8 on 2025-11-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='Суперадмин (владелец)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Telegram админ',
                'verbose_name_plural': 'Telegram админы',
                'ordering': ['-is_superadmin', 'full_name', 'telegram_user_id'],
            },
        ),
    ]
