# Generated by Django 5.2.8 on 2025-11-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramadmin',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=64, verbose_name='Username'),
        ),
    ]
